version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: xeno_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    command: npm run dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/xeno_db
      - JWT_SECRET=devsecret
      - PORT=4000
    depends_on:
      - db

volumes:
  db-data:
